// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	atseval "github.com/sriganeshlokesh/forged/pkg/atseval"

	mock "github.com/stretchr/testify/mock"
)

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

type MockEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngine) EXPECT() *MockEngine_Expecter {
	return &MockEngine_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function with given fields: ctx, jobDescription, resume
func (_m *MockEngine) Evaluate(ctx context.Context, jobDescription string, resume atseval.Resume) (*atseval.Evaluation, error) {
	ret := _m.Called(ctx, jobDescription, resume)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 *atseval.Evaluation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, atseval.Resume) (*atseval.Evaluation, error)); ok {
		return rf(ctx, jobDescription, resume)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, atseval.Resume) *atseval.Evaluation); ok {
		r0 = rf(ctx, jobDescription, resume)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*atseval.Evaluation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, atseval.Resume) error); ok {
		r1 = rf(ctx, jobDescription, resume)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEngine_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockEngine_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - jobDescription string
//   - resume atseval.Resume
func (_e *MockEngine_Expecter) Evaluate(ctx interface{}, jobDescription interface{}, resume interface{}) *MockEngine_Evaluate_Call {
	return &MockEngine_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, jobDescription, resume)}
}

func (_c *MockEngine_Evaluate_Call) Run(run func(ctx context.Context, jobDescription string, resume atseval.Resume)) *MockEngine_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(atseval.Resume))
	})
	return _c
}

func (_c *MockEngine_Evaluate_Call) Return(_a0 *atseval.Evaluation, _a1 error) *MockEngine_Evaluate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEngine_Evaluate_Call) RunAndReturn(run func(context.Context, string, atseval.Resume) (*atseval.Evaluation, error)) *MockEngine_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
