// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"github.com/google/wire"
	"github.com/sriganeshlokesh/forged/adapter/evaluator/stub"
	http2 "github.com/sriganeshlokesh/forged/api/http"
	"github.com/sriganeshlokesh/forged/api/http/handle"
	"github.com/sriganeshlokesh/forged/application/evaluation"
	"github.com/sriganeshlokesh/forged/config"
	"github.com/sriganeshlokesh/forged/domain/service"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

// InitializeServer is the wire injector that builds the complete *http.Server.
// wire.Build is replaced by generated code in wire_gen.go.
func InitializeServer(cfg *config.Config, logger *slog.Logger) *http.Server {
	healthHandler := handle.NewHealthHandler(cfg)
	stubEvaluator := stub.NewStubEvaluator()
	useCase := evaluation.NewUseCase(stubEvaluator)
	evaluationHandler := handle.NewEvaluationHandler(useCase, logger)
	handler := http2.NewRouter(logger, healthHandler, evaluationHandler)
	server := http2.NewServer(cfg, handler, logger)
	return server
}

// wire.go:

// ServerSet groups the providers needed to build an *http.Server.
var ServerSet = wire.NewSet(handle.NewHealthHandler, handle.NewEvaluationHandler, evaluation.NewUseCase, stub.NewStubEvaluator, wire.Bind(new(service.IResumeEvaluator), new(*stub.StubEvaluator)), http2.NewRouter, http2.NewServer)
