// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sriganeshlokesh/forged/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockResumeReviser is an autogenerated mock type for the ResumeReviser type
type MockResumeReviser struct {
	mock.Mock
}

type MockResumeReviser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResumeReviser) EXPECT() *MockResumeReviser_Expecter {
	return &MockResumeReviser_Expecter{mock: &_m.Mock}
}

// Revise provides a mock function with given fields: ctx, spec
func (_m *MockResumeReviser) Revise(ctx context.Context, spec model.RevisionSpec) (string, string, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Revise")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RevisionSpec) (string, string, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RevisionSpec) string); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RevisionSpec) string); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.RevisionSpec) error); ok {
		r2 = rf(ctx, spec)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockResumeReviser_Revise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revise'
type MockResumeReviser_Revise_Call struct {
	*mock.Call
}

// Revise is a helper method to define mock.On call
//   - ctx context.Context
//   - spec model.RevisionSpec
func (_e *MockResumeReviser_Expecter) Revise(ctx interface{}, spec interface{}) *MockResumeReviser_Revise_Call {
	return &MockResumeReviser_Revise_Call{Call: _e.mock.On("Revise", ctx, spec)}
}

func (_c *MockResumeReviser_Revise_Call) Run(run func(ctx context.Context, spec model.RevisionSpec)) *MockResumeReviser_Revise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RevisionSpec))
	})
	return _c
}

func (_c *MockResumeReviser_Revise_Call) Return(draftAfter string, rationale string, err error) *MockResumeReviser_Revise_Call {
	_c.Call.Return(draftAfter, rationale, err)
	return _c
}

func (_c *MockResumeReviser_Revise_Call) RunAndReturn(run func(context.Context, model.RevisionSpec) (string, string, error)) *MockResumeReviser_Revise_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResumeReviser creates a new instance of MockResumeReviser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResumeReviser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResumeReviser {
	mock := &MockResumeReviser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
