// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/sriganeshlokesh/forged/application/core"

	mock "github.com/stretchr/testify/mock"
)

// MockEvaluationUseCase is an autogenerated mock type for the EvaluationUseCase type
type MockEvaluationUseCase struct {
	mock.Mock
}

type MockEvaluationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluationUseCase) EXPECT() *MockEvaluationUseCase_Expecter {
	return &MockEvaluationUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockEvaluationUseCase) Execute(ctx context.Context, in core.Input) (core.Output, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 core.Output
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Input) (core.Output, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Input) core.Output); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Output)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Input) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvaluationUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEvaluationUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in core.Input
func (_e *MockEvaluationUseCase_Expecter) Execute(ctx interface{}, in interface{}) *MockEvaluationUseCase_Execute_Call {
	return &MockEvaluationUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockEvaluationUseCase_Execute_Call) Run(run func(ctx context.Context, in core.Input)) *MockEvaluationUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Input))
	})
	return _c
}

func (_c *MockEvaluationUseCase_Execute_Call) Return(_a0 core.Output, _a1 error) *MockEvaluationUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvaluationUseCase_Execute_Call) RunAndReturn(run func(context.Context, core.Input) (core.Output, error)) *MockEvaluationUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEvaluationUseCase creates a new instance of MockEvaluationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluationUseCase {
	mock := &MockEvaluationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
